modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "anyfreetype"
version = "${version}"
displayName = "AnyFreeType"
authors = "Gaming32"
description = '''
Allows any TrueType font to be loaded, not just ttf files
'''
logoFile = "assets/anyfreetype/icon.png"

[[dependencies.anyfreetype]]
modId = "neoforge"
type = "required"
ordering = "NONE"
side = "BOTH"

[[dependencies.anyfreetype]]
modId = "minecraft"
type = "required"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "anyfreetype.mixins.json"
